
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  run-rubocop:
  test-ruby:
    docker:
      - image: cimg/ruby:2.7.7
      - image: cimg/postgres:13.3
    environment:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_DB: expense_split_api_test
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 5432 && echo "Postgres is up" && exit 0
              echo "Waiting for Postgres..."
              sleep 1
            done
            echo "Failed to connect to Postgres" && exit 1
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
            bundle exec rake db:test:prepare
      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  rubocop:
    docker:
      - image: cimg/ruby:2.7.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

workflows:
  build-and-test:
    jobs:
      - rubocop
      - test-ruby:
          requires:
            - rubocop
